# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Liber' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Liber
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Database'
  pod 'Charts'

end
